# Generated by Django 3.1.5 on 2021-01-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('kitchen', 'Kitchen'), ('counter', 'Counter')], default='Kitchen', max_length=10, null=True),
        ),
    ]
