# Generated by Django 2.2.10 on 2021-01-13 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210113_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='approve',
        ),
    ]
