# Generated by Django 2.2.10 on 2021-01-13 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_order_approve'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
